[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flecs_api = { path = "../flecs_api/" }
tokio = {version = "1.18.2", features = ["full"] }
