/*
 * FLECS Daemon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-beta.4
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AppListGet200Response {
    #[serde(rename = "additionalInfo", skip_serializing_if = "Option::is_none")]
    pub additional_info: Option<String>,
    #[serde(rename = "appList", skip_serializing_if = "Option::is_none")]
    pub app_list: Option<Vec<crate::models::InstalledApp>>,
}

impl AppListGet200Response {
    pub fn new() -> AppListGet200Response {
        AppListGet200Response {
            additional_info: None,
            app_list: None,
        }
    }
}


