/*
 * FLECS Daemon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-beta.4
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AppListGet200ResponseAllOf {
    #[serde(rename = "appList", skip_serializing_if = "Option::is_none")]
    pub app_list: Option<Vec<crate::models::InstalledApp>>,
}

impl AppListGet200ResponseAllOf {
    pub fn new() -> AppListGet200ResponseAllOf {
        AppListGet200ResponseAllOf {
            app_list: None,
        }
    }
}


