/*
 * FLECS Daemon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-beta.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AdditionalInfo : Additional info



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AdditionalInfo {
    #[serde(rename = "additionalInfo", skip_serializing_if = "Option::is_none")]
    pub additional_info: Option<String>,
}

impl AdditionalInfo {
    /// Additional info
    pub fn new() -> AdditionalInfo {
        AdditionalInfo {
            additional_info: None,
        }
    }
}


