/*
 * FLECS Daemon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-beta.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// App : App name



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct App {
    #[serde(rename = "app", skip_serializing_if = "Option::is_none")]
    pub app: Option<String>,
}

impl App {
    /// App name
    pub fn new() -> App {
        App {
            app: None,
        }
    }
}


