/*
 * FLECS Daemon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-beta.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AppInstances : App instances



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AppInstances {
    #[serde(rename = "desired", skip_serializing_if = "Option::is_none")]
    pub desired: Option<String>,
    #[serde(rename = "instanceId", skip_serializing_if = "Option::is_none")]
    pub instance_id: Option<String>,
    #[serde(rename = "instanceName", skip_serializing_if = "Option::is_none")]
    pub instance_name: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}

impl AppInstances {
    /// App instances
    pub fn new() -> AppInstances {
        AppInstances {
            desired: None,
            instance_id: None,
            instance_name: None,
            status: None,
            version: None,
        }
    }
}


