/*
 * FLECS Daemon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-beta.4
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AppInstancesAllOf {
    #[serde(rename = "desired", skip_serializing_if = "Option::is_none")]
    pub desired: Option<String>,
}

impl AppInstancesAllOf {
    pub fn new() -> AppInstancesAllOf {
        AppInstancesAllOf {
            desired: None,
        }
    }
}


