/*
 * FLECS Daemon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-beta.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Conffiles : Bind-mounted configuration files of an instance



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Conffiles {
    #[serde(rename = "conffiles", skip_serializing_if = "Option::is_none")]
    pub conffiles: Option<Vec<crate::models::ConffilesConffilesInner>>,
}

impl Conffiles {
    /// Bind-mounted configuration files of an instance
    pub fn new() -> Conffiles {
        Conffiles {
            conffiles: None,
        }
    }
}


