/*
 * FLECS Daemon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-beta.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Hostname : Hostname of an instance



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Hostname {
    #[serde(rename = "hostname", skip_serializing_if = "Option::is_none")]
    pub hostname: Option<String>,
}

impl Hostname {
    /// Hostname of an instance
    pub fn new() -> Hostname {
        Hostname {
            hostname: None,
        }
    }
}


