/*
 * FLECS Daemon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-beta.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// InstanceName : Instance name



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InstanceName {
    #[serde(rename = "instanceName", skip_serializing_if = "Option::is_none")]
    pub instance_name: Option<String>,
}

impl InstanceName {
    /// Instance name
    pub fn new() -> InstanceName {
        InstanceName {
            instance_name: None,
        }
    }
}


