/*
 * FLECS Daemon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-beta.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// InstanceId : Instance ID



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InstanceId {
    #[serde(rename = "instanceId", skip_serializing_if = "Option::is_none")]
    pub instance_id: Option<String>,
}

impl InstanceId {
    /// Instance ID
    pub fn new() -> InstanceId {
        InstanceId {
            instance_id: None,
        }
    }
}


