/*
 * FLECS Daemon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-beta.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// InstalledApp : Installed app metadata



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InstalledApp {
    #[serde(rename = "app", skip_serializing_if = "Option::is_none")]
    pub app: Option<String>,
    #[serde(rename = "versions", skip_serializing_if = "Option::is_none")]
    pub versions: Option<Vec<crate::models::AppVersions>>,
    #[serde(rename = "instances", skip_serializing_if = "Option::is_none")]
    pub instances: Option<Vec<crate::models::AppInstances>>,
}

impl InstalledApp {
    /// Installed app metadata
    pub fn new() -> InstalledApp {
        InstalledApp {
            app: None,
            versions: None,
            instances: None,
        }
    }
}


