/*
 * FLECS Daemon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-beta.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IpAddress : IP address of an instance



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IpAddress {
    #[serde(rename = "ipAddress", skip_serializing_if = "Option::is_none")]
    pub ip_address: Option<String>,
}

impl IpAddress {
    /// IP address of an instance
    pub fn new() -> IpAddress {
        IpAddress {
            ip_address: None,
        }
    }
}


