/*
 * FLECS Daemon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-beta.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// LicenseKey : License key for app installation



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LicenseKey {
    #[serde(rename = "licenseKey", skip_serializing_if = "Option::is_none")]
    pub license_key: Option<String>,
}

impl LicenseKey {
    /// License key for app installation
    pub fn new() -> LicenseKey {
        LicenseKey {
            license_key: None,
        }
    }
}


