/*
 * FLECS Daemon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-beta.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Mounts : Bind mounts of an instance



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Mounts {
    #[serde(rename = "mounts", skip_serializing_if = "Option::is_none")]
    pub mounts: Option<Vec<crate::models::MountsMountsInner>>,
}

impl Mounts {
    /// Bind mounts of an instance
    pub fn new() -> Mounts {
        Mounts {
            mounts: None,
        }
    }
}


