/*
 * FLECS Daemon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-beta.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Ports : Allocated network ports of an instance



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Ports {
    #[serde(rename = "ports", skip_serializing_if = "Option::is_none")]
    pub ports: Option<Vec<crate::models::PortsPortsInner>>,
}

impl Ports {
    /// Allocated network ports of an instance
    pub fn new() -> Ports {
        Ports {
            ports: None,
        }
    }
}


