/*
 * FLECS Daemon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-beta.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Version : App version



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Version {
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}

impl Version {
    /// App version
    pub fn new() -> Version {
        Version {
            version: None,
        }
    }
}


